//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ISS22
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид поддержки.
    /// </summary>
    // *** Start programmer edit section *** (ВидПоддержки CustomAttributes)

    // *** End programmer edit section *** (ВидПоддержки CustomAttributes)
    [AutoAltered()]
    [Caption("Вид поддержки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВидПоддержкиE", new string[] {
            "Наименование as \'Наименование\'",
            "Описание as \'Описание\'",
            "Форма as \'Форма\'",
            "Форма.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Форма.Наименование"})]
    [AssociatedDetailViewAttribute("ВидПоддержкиE", "СписокУсловий", "СписокУсловийE", true, "", "Список условий", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ВидПоддержкиE", "Форма", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ВидПоддержкиL", new string[] {
            "Наименование as \'Наименование\'",
            "Описание as \'Описание\'",
            "Форма.Наименование as \'Наименование\'"})]
    public class ВидПоддержки : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fОписание;
        
        private IIS.ISS22.Форма fФорма;
        
        private IIS.ISS22.DetailArrayOfСписокУсловий fСписокУсловий;
        
        // *** Start programmer edit section *** (ВидПоддержки CustomMembers)

        // *** End programmer edit section *** (ВидПоддержки CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ВидПоддержки.Наименование CustomAttributes)

        // *** End programmer edit section *** (ВидПоддержки.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ВидПоддержки.Наименование Get start)

                // *** End programmer edit section *** (ВидПоддержки.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ВидПоддержки.Наименование Get end)

                // *** End programmer edit section *** (ВидПоддержки.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидПоддержки.Наименование Set start)

                // *** End programmer edit section *** (ВидПоддержки.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ВидПоддержки.Наименование Set end)

                // *** End programmer edit section *** (ВидПоддержки.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (ВидПоддержки.Описание CustomAttributes)

        // *** End programmer edit section *** (ВидПоддержки.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (ВидПоддержки.Описание Get start)

                // *** End programmer edit section *** (ВидПоддержки.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (ВидПоддержки.Описание Get end)

                // *** End programmer edit section *** (ВидПоддержки.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидПоддержки.Описание Set start)

                // *** End programmer edit section *** (ВидПоддержки.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (ВидПоддержки.Описание Set end)

                // *** End programmer edit section *** (ВидПоддержки.Описание Set end)
            }
        }
        
        /// <summary>
        /// Вид поддержки.
        /// </summary>
        // *** Start programmer edit section *** (ВидПоддержки.Форма CustomAttributes)

        // *** End programmer edit section *** (ВидПоддержки.Форма CustomAttributes)
        [NotNull()]
        public virtual IIS.ISS22.Форма Форма
        {
            get
            {
                // *** Start programmer edit section *** (ВидПоддержки.Форма Get start)

                // *** End programmer edit section *** (ВидПоддержки.Форма Get start)
                IIS.ISS22.Форма result = this.fФорма;
                // *** Start programmer edit section *** (ВидПоддержки.Форма Get end)

                // *** End programmer edit section *** (ВидПоддержки.Форма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидПоддержки.Форма Set start)

                // *** End programmer edit section *** (ВидПоддержки.Форма Set start)
                this.fФорма = value;
                // *** Start programmer edit section *** (ВидПоддержки.Форма Set end)

                // *** End programmer edit section *** (ВидПоддержки.Форма Set end)
            }
        }
        
        /// <summary>
        /// Вид поддержки.
        /// </summary>
        // *** Start programmer edit section *** (ВидПоддержки.СписокУсловий CustomAttributes)

        // *** End programmer edit section *** (ВидПоддержки.СписокУсловий CustomAttributes)
        public virtual IIS.ISS22.DetailArrayOfСписокУсловий СписокУсловий
        {
            get
            {
                // *** Start programmer edit section *** (ВидПоддержки.СписокУсловий Get start)

                // *** End programmer edit section *** (ВидПоддержки.СписокУсловий Get start)
                if ((this.fСписокУсловий == null))
                {
                    this.fСписокУсловий = new IIS.ISS22.DetailArrayOfСписокУсловий(this);
                }
                IIS.ISS22.DetailArrayOfСписокУсловий result = this.fСписокУсловий;
                // *** Start programmer edit section *** (ВидПоддержки.СписокУсловий Get end)

                // *** End programmer edit section *** (ВидПоддержки.СписокУсловий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидПоддержки.СписокУсловий Set start)

                // *** End programmer edit section *** (ВидПоддержки.СписокУсловий Set start)
                this.fСписокУсловий = value;
                // *** Start programmer edit section *** (ВидПоддержки.СписокУсловий Set end)

                // *** End programmer edit section *** (ВидПоддержки.СписокУсловий Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВидПоддержкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВидПоддержкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВидПоддержкиE", typeof(IIS.ISS22.ВидПоддержки));
                }
            }
            
            /// <summary>
            /// "ВидПоддержкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВидПоддержкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВидПоддержкиL", typeof(IIS.ISS22.ВидПоддержки));
                }
            }
        }
    }
}
